### ISSUE TITLE
qtip functionality for mobile

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#25]
Currently qtip is set to on hover for tooltips around the site, this needs to be changed to on click for mobile view.

qtip config-
show: 'click'

Example: Progress Notes - Role Centre (i.e Green Flags)

**Comment by paulfisher53** [comment]
I've made a change to load the QTip library in mobile mode. Please load these files: [Mobile QTip.zip](https://github.com/LiveappSolutions/Liveapp/files/1425641/Mobile.QTip.zip)

I have tested using this code:

```javascript
if(viewer.GetPageGrid()){
  viewer.GetPageGrid().OnBindRow = function(rowid,data,element){
    $(element).children().each( function( index, e ){
      var cell = $(e);
      var opts = { 
        position: { at: 'bottom left' },
        style: { tip: { corner: false}, classes: "app-tooltip-text" },
        content: {text: cell.html()}
      };
      if(Application.IsInMobile()){
        opts.show =  {event: 'taphold'};
      }
      cell.qtip(opts);
    });    
  };
}
```

Note: I used `taphold` instead of `click`, as click was already used on my grid to edit the row

**Comment by JasonBev** [comment]
Qtip functionality for mobile working as expected

**Comment by paulfisher53** [comment]
Thanks
