### ISSUE TITLE
Convert NewColumnOrder function to Mobile

### ISSUE THREAD

**Issue by JasonBev** [LiveappSolutions/Liveapp#7]
For use in client plan line sorting for mobile view

**Comment by paulfisher53** [comment]
Done. Please merge this [Fix.zip](https://github.com/LiveappSolutions/Liveapp/files/827144/Fix.zip)

**Comment by paulfisher53** [comment]
Found an issue where the mobile function is not taking into account the row selector.

**Comment by paulfisher53** [comment]
Here's the new fix that takes into account the row selector [SortFix.zip](https://github.com/LiveappSolutions/Liveapp/files/1126382/SortFix.zip)

**Comment by paulfisher53** [comment]
I still get the same issue with the new fix.
 
e.g In screenshot below the value will have the 13 (left image). When i=1 it’s looking for the item number 12 which doesn’t exist in m_cols (right image) so it still pushes the undefined object to new_cols and new_colNames. Rather than skipping 0 and starting at 1 I need to remove the last value of the array before existing sort passes it in I guess.

![image](https://user-images.githubusercontent.com/25142601/28097655-df94970a-66f4-11e7-8354-d2c114cb4283.png)

**Comment by paulfisher53** [comment]
Closed, check https://github.com/LiveappSolutions/Liveapp/commit/af1c1cc05a95081aaa29f6583a1e250cd43a54f8 for the fix
